### ISSUE TITLE
The <from> and <version> directive is mandatory in your travis config

### ISSUE THREAD

**Issue by abitrolly** [PaulRosset/previs#7]
`previs` doesn't start.
```
✗ previs
You are using '.travis.yml' file
Creating Dockerfile
The <from> and <version> directive is mandatory in your travis config%          
```
What does that mean?

I am using snap `beta:      0.4.1 (77) 3MB - <`.

**Comment by PaulRosset** [comment]
Hey, thank's for your feedback.
This error report mean either you forgot to pass the language and the version of the language used or either you just passed the things in a manner that Previs don't understand.

**Comment by abitrolly** [comment]
Here is the `.travis.yml` - https://github.com/Multy-io/Multy-back/blob/fb4fa80244144444c28f258bd8711ff42bc504fd/.travis.yml - it is the same as in `master` right now, so you clone and run it yourself.

**Comment by PaulRosset** [comment]
I think you should read the readme and the wiki. Many things in your travis.yml is not yet supported by Previs.

**Comment by abitrolly** [comment]
I could write a patch for this specific message if I could understand where is comes from.
